export * as Carves from './carves';
export * as Corrodes from './corrodes';
export * as Freezes from './freezes';
export * as Ignites from './ignites';
export * as Smashes from './smashes';
export * as Tailors from './tailors';
export * as Unlocks from './unlocks';
export * as Wets from './wets';
export * as Zaps from './zaps';
